modLoader="kotlinforforge"
loaderVersion="${loaderVersionRange}"
license="${modLicense}"

[[mods]]
modId="${modId}"
version="${modVersion}"
displayName="${modName}"
authors="${modAuthors}"
description='''${modDescription}'''

#[[mixins]]
#config="${modId}.mixins.json"

#[[accessTransformers]]
#file="META-INF/accesstransformer.cfg"

[[dependencies.${modId}]]
    modId="neoforge"
    type="required"
    versionRange="${neoVersionRange}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${modId}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraftVersionRange}"
    ordering="NONE"
    side="BOTH"
